{
 "title": "My Sungrow Wechselrichter",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Solar-String-Leistungen",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "String 1",
     "measurement": "PV",
     "query": "SELECT last(\"Spannung\") , 'Netzspannung'  FROM \"Netz\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Leistung1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "String 1" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "String 2",
     "measurement": "PV",
     "select": [
      [
       { "params": [ "Leistung2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "String 2" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "230 Volt Wechselrichter",
   "type": "table",
   "gridPos": { "h": 4, "w": 15, "x": 5, "y": 0 },
   "targets": [
    {
     "alias": "Spannung",
     "measurement": "AC",
     "query": "SELECT last(\"Spannung\") , 'Netzspannung'  FROM \"Netz\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Spannung_R" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Spannung" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "Frequenz",
     "measurement": "AC",
     "select": [
      [
       { "params": [ "Frequenz" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Frequenz" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "WR-Leistung",
     "measurement": "AC",
     "select": [
      [
       { "params": [ "Leistung" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Leistung" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Batterie SOC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "Batterie",
     "select": [
      [
       { "params": [ "SOC" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 20, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "String 1",
     "measurement": "PV",
     "query": "SELECT last(\"Spannung\") , 'Netzspannung'  FROM \"Netz\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Leistung" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "PV-Leistung" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "String 2",
     "measurement": "AC",
     "select": [
      [
       { "params": [ "Hausverbrauch" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Hausverbrauch" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "String 3",
     "measurement": "AC",
     "select": [
      [
       { "params": [ "Einspeisung" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Einspeisung" ], "type": "alias" }
      ]
     ]
    },
    {
     "measurement": "AC",
     "select": [
      [
       { "params": [ "Bezug" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Bezug" ], "type": "alias" }
      ]
     ]
    },
    {
     "measurement": "Batterie",
     "select": [
      [
       { "params": [ "EntladeLeistung" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Batterie Entl." ], "type": "alias" }
      ]
     ]
    },
    {
     "measurement": "Batterie",
     "select": [
      [
       { "params": [ "LadeLeistung" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Batt. Ladung" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperatur",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "Service",
     "select": [
      [
       { "params": [ "Temperatur" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "erzeugte PV Leistung, Hausverbrauch und Batterie SOC",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "erzeugte Leistung",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PV",
     "select": [
      [
       { "params": [ "Leistung" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Hausverbrauch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AC",
     "select": [
      [
       { "params": [ "Hausverbrauch" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "SOC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Batterie",
     "select": [
      [
       { "params": [ "SOC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Erzeugte PV Leistung",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Energie von Heute",
     "measurement": "Summen",
     "select": [
      [
       { "params": [ "Wh_GesamtHeute" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Heute" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "Energie gesamt",
     "measurement": "Summen",
     "select": [
      [
       { "params": [ "Wh_Gesamt" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Gesamt" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tagesleistung",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Erzeugt",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Summen",
     "select": [
      [
       { "params": [ "Wh_GesamtHeute" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Eingespeist",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AC",
     "select": [
      [
       { "params": [ "Einspeisung" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  }
 ]
}